### ISSUE TITLE
Blocking an entire page with either a custom replacement or redaction, blocks images as well

### ISSUE THREAD

**Issue by acornestean** [mozilla/fireblocks#17]
Description:
Blocking an entire page causes images to be blocked as well.

Steps to reproduce:
1. Access https://fr.wikipedia.org/wiki/Jules_Ladoum%C3%A8gue
2. Create any rule and make sure the replace option is “Block entire page” and enable it
3. Notice images are blocked as well

Actual:
Blocking an entire page causes images to be blocked as well.

Expected:
Since the add-on blocks text, images should remain intact.

![2023-09-22_11h33_09](https://github.com/mozilla/fireblocks/assets/50236075/b6e34959-f23b-4894-9ee2-7a8ecad306ea)

![2023-09-22_11h32_54](https://github.com/mozilla/fireblocks/assets/50236075/b8ed4a36-ca51-4822-9f79-de037a52665e)

**Comment by GregSherman** [comment]
This is intentional as information can still be conveyed through images. In the other block settings, images are censored if their metadata contains the block phrase as well.
