### ISSUE TITLE
Rules created for different pages are displayed undifferentiated in the add-on panel

### ISSUE THREAD

**Issue by acornestean** [mozilla/fireblocks#18]
Description:
The rules created for different pages are all displayed in the add-on panel with no indication as to which rule is for which website/page.

Steps to reproduce:
1. Access https://fr.wikipedia.org/wiki/Jules_Ladoum%C3%A8gue and create a random rule
2. Access https://fr.wikipedia.org/wiki/Drapeau_du_Turkm%C3%A9nistan and crate a random rule
3. Access https://www.facebook.com/ and create a random rule
3. On any of the 3 pages, open the add-on panel and notice that all rules are displayed in the panel with no indication which rule is for which website

Actual:
There is no indication as to which rule is for which site.

Expected:
A section should be added in the add-on panel to indicate which rule is active on which site.

**Comment by GregSherman** [comment]
There's no current plan to have per-site rules. With the limitation of the browser, I believe I can only edit the contents of the active window. If you were to refresh each page, all 3 rules become active on all pages. Or re-enabling. Ideally all 3 change immediately
